#
# This file is the manifest to determine which built items are copied to the
# hosted/Box file server locations. The versions that are specified within
# parenthesis below *must* match the versions from the version.properties file.
# They can also be overridden by passing values to the harvester script. ${see -versions}.
# It is best to keep the files and folders alphabetized because it makes it easier
# to compare the manifest to the filesystem. The exception to this is the ee/ce folder
# since most of the important artifacts are in the ee folder.
#

#EE Stuff
ee:
    client-tools:
        - pad-ee-${platform.version}.zip
        - pdi-ee-client-${platform.version}.zip
        - pdi-ee-client-${platform.version}-hadoop-addon.zip
        - pentaho-analysis-ee-${platform.version}.zip
        - pentaho-big-data-ee-package-${platform.version}.zip
        - pme-ee-${platform.version}.zip
        - pme-ee-${platform.version}-hadoop-addon.zip
        - prd-ee-${platform.version}.zip
        - prd-ee-${platform.version}-hadoop-addon.zip
        - psw-ee-${mondrian.version}.zip
    installers:
        - pentaho-business-analytics-${platform.version}-x64.app.tar.gz
        - pentaho-business-analytics-${platform.version}-x64.bin
        - pentaho-business-analytics-${platform.version}-x64.exe
        - pentaho-update-${platform.version}-Windows.zip
        - pentaho-update-${platform.version}-Linux.zip
    other:
        - pentaho-operations-mart-${platform.version}.zip
        - pentaho-sdk-${platform.version}.zip
        - dock-maker-${platform.version}-internal.zip
        - dock-maker-${platform.version}-public.zip
    plugins:
        - paz-plugin-ee-${platform.version}.zip
        - pdd-plugin-ee-${platform.version}.zip
        - pdi-ee-plugin-${platform.version}.zip
        - pentaho-monitoring-plugin-mib-assembly-${platform.version}.zip
        - pir-plugin-ee-${platform.version}.zip
        - hierarchical-datatype-plugin-${platform.version}.zip
        - pentaho-streaming-kafka-plugin-zip-${platform.version}.zip
        - elasticsearch-rest-plugin-${platform.version}.zip
        - kafka-job-plugins-${platform.version}.zip
    server:
        - pentaho-server-ee-${platform.version}.zip
        - pentaho-server-manual-ee-${platform.version}.zip
    shims:
        - pentaho-hadoop-shims-ee-cdh61-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-emr521-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-hdp30-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-dataproc1421-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-cdpdc71-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-hdi40-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-apachevanilla-kar-${pentaho-hadoop-shims.version}.kar
        - pentaho-hadoop-shims-ee-emr700-kar-${pentaho-hadoop-shims.version}.kar


#CE Stuff
ce:
    client-tools:
        - pad-ce-${platform.version}.zip
        - pdi-ce-${platform.version}.zip
        - pdi-ce-${platform.version}-hadoop-addon.zip
        - pentaho-big-data-plugin-${platform.version}.zip
        - pme-ce-${platform.version}.zip
        - pme-ce-${platform.version}-hadoop-addon.zip
        - prd-ce-${platform.version}.zip
        - prd-ce-${platform.version}-hadoop-addon.zip
        - psw-ce-${mondrian.version}.zip
    plugins:
        - kettle-sdk-plugin-assembly-${platform.version}.zip
    server:
        - pentaho-server-ce-${platform.version}.zip
        - pentaho-server-manual-ce-${platform.version}.zip
    other:
        - pre-classic-sdk-${platform.version}.zip

# Testable items, but not customer hand-off items
not-for-release:
    - pdi-ee-client-${platform.version}-osgi.zip
    - pme-ee-${platform.version}-osgi.zip
    - prd-ee-${platform.version}-osgi.zip
    - pdi-ce-${platform.version}-osgi.zip
    - pme-ce-${platform.version}-osgi.zip
    - prd-ce-${platform.version}-osgi.zip