version: '3.7'

networks:
  pipelines:
    name: ${NETWORK_NAME:-hv-pipelines}

volumes:
  workspace:
    name: ${WORK_VOLUME_NAME:-hv-jenkins-workspace}
  home:
    name: ${HOME_VOLUME_NAME:-hv-jenkins-home}

services:
  master:
    image: ${MASTER_IMAGE_NAME:-hv/jenkins-master}
    build:
      context: ../../jenkins
      args:
        - version=${JENKINS_VERSION:-lts}
    environment:
      - MASTER_LABELS=${MASTER_LABELS:-master}
    env_file:
      - .env
    volumes:
      - home:/var/jenkins_home
      - ${PROJECTS_DIR:-./projects}:/projects
    networks:
      - pipelines
    ports:
      - ${PORT:-8080}:8080
  agent:
    image: ${AGENT_IMAGE_NAME:-hv/jenkins-agent}
    build:
      context: ../../jenkins/agent
      args:
        - uid=${UID:-1000}
        - gid=${GID:-1000}
        - home=/jenkins
    env_file:
      - .env
    command: >
      -master http://master:8080
      -fsroot /jenkins
      -executors ${AGENT_EXECUTORS:-2}
      -name agent
      -labels ${AGENT_LABELS:-non-master}
    volumes:
      - workspace:/jenkins/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROJECTS_DIR:-./projects}:/projects
    networks:
      - pipelines
